$(phplibdir)/zend.la: ./zend.la
	$(LIBTOOL) --mode=install cp ./zend.la $(phplibdir)

./zend.la: $(shared_objects_zend) $(ZEND_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_zend) $(ZEND_SHARED_LIBADD)

